"""re-add join tables

Revision ID: 0161f3ccb3c5
Revises: 638f6761a069
Create Date: 2024-05-05 12:21:33.604107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0161f3ccb3c5'
down_revision = '638f6761a069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_bands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('band_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['band_id'], ['bands.id'], name=op.f('fk_users_bands_band_id_bands')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_users_bands_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users_bands'))
    )
    op.create_table('songs_users_instruments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_songs_users_instruments_instrument_id_instruments')),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], name=op.f('fk_songs_users_instruments_song_id_songs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_songs_users_instruments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_songs_users_instruments'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songs_users_instruments')
    op.drop_table('users_bands')
    # ### end Alembic commands ###
