"""empty message

Revision ID: 0e981eb8b1e1
Revises: 550ab8eb956e
Create Date: 2024-05-22 13:36:41.068784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e981eb8b1e1'
down_revision = '550ab8eb956e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_instruments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_instruments',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('instrument_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name='fk_users_instruments_instrument_id_instruments'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_users_instruments_user_id_users'),
    sa.PrimaryKeyConstraint('user_id', 'instrument_id', name='pk_users_instruments')
    )
    # ### end Alembic commands ###
