"""add id columns to join tables

Revision ID: 246f4ed1648f
Revises: 6059370eeb5e
Create Date: 2024-05-05 12:02:59.829107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '246f4ed1648f'
down_revision = '6059370eeb5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs_users_instruments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False, autoincrement=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('instrument_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('song_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('users_bands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False, autoincrement=True))
        batch_op.alter_column('user_id', existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column('band_id', existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_bands', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('songs_users_instruments', schema=None) as batch_op:
        batch_op.alter_column('song_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('instrument_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('id')

    # ### end Alembic commands ###
