"""empty message

Revision ID: 3808d2ab8732
Revises: 0161f3ccb3c5
Create Date: 2024-05-05 13:44:47.836911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3808d2ab8732'
down_revision = '0161f3ccb3c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs_users_instruments', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('users_bands', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_bands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))

    with op.batch_alter_table('songs_users_instruments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
