"""empty message

Revision ID: 5cc9f47d7cb9
Revises: 72149b099316
Create Date: 2024-05-22 15:44:06.831465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cc9f47d7cb9'
down_revision = '72149b099316'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_instruments', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('instrument_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('unique_user_instrument', type_='unique')
        batch_op.drop_column('proficiency')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_instruments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('proficiency', sa.VARCHAR(), nullable=False))
        batch_op.create_unique_constraint('unique_user_instrument', ['user_id', 'instrument_id'])
        batch_op.alter_column('instrument_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
