"""empty message

Revision ID: 617701386957
Revises: e022907482e1
Create Date: 2024-05-22 13:40:19.187204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '617701386957'
down_revision = 'e022907482e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('proficiency', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_users_instruments_instrument_id_instruments')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_users_instruments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users_instruments'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_instruments')
    # ### end Alembic commands ###
