"""add uniqueConstraint to user_id, instrument_id

Revision ID: 72149b099316
Revises: 617701386957
Create Date: 2024-05-22 13:57:21.508747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72149b099316'
down_revision = '617701386957'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_instruments', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('instrument_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint('unique_user_instrument', ['user_id', 'instrument_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_instruments', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_instrument', type_='unique')
        batch_op.alter_column('instrument_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
