"""remove join tables

Revision ID: 7c727267137e
Revises: b2ea62db5870
Create Date: 2024-05-05 15:03:40.469479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c727267137e'
down_revision = 'b2ea62db5870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_bands')
    op.drop_table('songs_users_instruments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs_users_instruments',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('instrument_id', sa.INTEGER(), nullable=False),
    sa.Column('song_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name='fk_songs_users_instruments_instrument_id_instruments'),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], name='fk_songs_users_instruments_song_id_songs'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_songs_users_instruments_user_id_users'),
    sa.PrimaryKeyConstraint('user_id', 'instrument_id', 'song_id', name='pk_songs_users_instruments')
    )
    op.create_table('users_bands',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('band_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['band_id'], ['bands.id'], name='fk_users_bands_band_id_bands'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_users_bands_user_id_users'),
    sa.PrimaryKeyConstraint('user_id', 'band_id', name='pk_users_bands')
    )
    # ### end Alembic commands ###
