"""empty message

Revision ID: aa36bc22fd68
Revises: 0e981eb8b1e1
Create Date: 2024-05-22 13:38:28.752075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa36bc22fd68'
down_revision = '0e981eb8b1e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proficiency', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users_instruments'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_instruments')
    # ### end Alembic commands ###
