"""add band_id to Song table

Revision ID: aafa73bb6130
Revises: e48a9b88fff7
Create Date: 2024-05-02 17:22:52.742910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aafa73bb6130'
down_revision = 'e48a9b88fff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('band_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_songs_band_id_bands'), 'bands', ['band_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_songs_band_id_bands'), type_='foreignkey')
        batch_op.drop_column('band_id')

    # ### end Alembic commands ###
