"""empty message

Revision ID: b31489b24e37
Revises: 3808d2ab8732
Create Date: 2024-05-05 13:46:20.935390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b31489b24e37'
down_revision = '3808d2ab8732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_bands')
    op.drop_table('songs_users_instruments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs_users_instruments',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('instrument_id', sa.INTEGER(), nullable=False),
    sa.Column('song_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name='fk_songs_users_instruments_instrument_id_instruments'),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], name='fk_songs_users_instruments_song_id_songs'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_songs_users_instruments_user_id_users')
    )
    op.create_table('users_bands',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('band_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['band_id'], ['bands.id'], name='fk_users_bands_band_id_bands'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_users_bands_user_id_users')
    )
    # ### end Alembic commands ###
